name: Environment Variables Demo

on:
  push:
    branches:
      - feature/createreg
  
jobs:
  demo:

    runs-on: ubuntu-latest
    env:
      APP_NAME: learning-storage
      LOCATION: uksouth
    
    steps:
      - name: Print APP_NAME
        run: |
          echo $APP_NAME
          echo $LOCATION
